### Homework
#### consumer_electronics_sales_data

In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('consumer_electronics_sales_data.csv')
data

,ProductID,ProductCategory,ProductBrand,ProductPrice,CustomerAge,CustomerGender,PurchaseFrequency,CustomerSatisfaction,PurchaseIntent
0,5874,Smartphones,Other Brands,312.949668,18,0,2,1,0
1,5875,Smart Watches,Samsung,980.389404,35,1,7,2,1
2,5876,Tablets,Samsung,2606.718293,63,0,1,5,1
3,5877,Smartphones,Samsung,870.395450,63,1,10,3,1
4,5878,Tablets,Sony,1798.955875,57,0,17,3,0
...,...,...,...,...,...,...,...,...,...
8995,14869,Smart Watches,Samsung,1041.149163,36,1,16,4,0
8996,14870,Smartphones,Samsung,1485.694311,57,0,5,1,1
8997,14871,Headphones,Samsung,2887.369597,28,0,18,4,0
8998,14872,Tablets,HP,1490.453964,38,0,4,2,1
8999,14873,Smartphones,Sony,2315.583087,62,0,15,2,1

In [3]:
data['ProductCategory'].value_counts()

ProductCategory
Laptops          1842
Smartphones      1841
Smart Watches    1810
Tablets          1769
Headphones       1738
Name: count, dtype: int64

In [4]:
data['ProductBrand'].value_counts()

ProductBrand
Samsung         1854
HP              1820
Sony            1790
Other Brands    1776
Apple           1760
Name: count, dtype: int64

In [5]:
data = pd.get_dummies(data, columns = ['ProductCategory'], dtype = 'int8')

In [6]:
data = pd.get_dummies(data, columns = ['ProductBrand'], dtype = 'int8')

In [7]:
data

,ProductID,ProductPrice,CustomerAge,CustomerGender,PurchaseFrequency,CustomerSatisfaction,PurchaseIntent,ProductCategory_Headphones,ProductCategory_Laptops,ProductCategory_Smart Watches,ProductCategory_Smartphones,ProductCategory_Tablets,ProductBrand_Apple,ProductBrand_HP,ProductBrand_Other Brands,ProductBrand_Samsung,ProductBrand_Sony
0,5874,312.949668,18,0,2,1,0,0,0,0,1,0,0,0,1,0,0
1,5875,980.389404,35,1,7,2,1,0,0,1,0,0,0,0,0,1,0
2,5876,2606.718293,63,0,1,5,1,0,0,0,0,1,0,0,0,1,0
3,5877,870.395450,63,1,10,3,1,0,0,0,1,0,0,0,0,1,0
4,5878,1798.955875,57,0,17,3,0,0,0,0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8995,14869,1041.149163,36,1,16,4,0,0,0,1,0,0,0,0,0,1,0
8996,14870,1485.694311,57,0,5,1,1,0,0,0,1,0,0,0,0,1,0
8997,14871,2887.369597,28,0,18,4,0,1,0,0,0,0,0,0,0,1,0
8998,14872,1490.453964,38,0,4,2,1,0,0,0,0,1,0,1,0,0,0
8999,14873,2315.583087,62,0,15,2,1,0,0,0,1,0,0,0,0,0,1

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9000 entries, 0 to 8999
Data columns (total 17 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ProductID                      9000 non-null   int64
 1   ProductPrice                   9000 non-null   float64
 2   CustomerAge                    9000 non-null   int64
 3   CustomerGender                 9000 non-null   int64
 4   PurchaseFrequency              9000 non-null   int64
 5   CustomerSatisfaction           9000 non-null   int64
 6   PurchaseIntent                 9000 non-null   int64
 7   ProductCategory_Headphones     9000 non-null   int8
 8   ProductCategory_Laptops        9000 non-null   int8
 9   ProductCategory_Smart Watches  9000 non-null   int8
 10  ProductCategory_Smartphones    9000 non-null   int8
 11  ProductCategory_Tablets        9000 non-null   int8
 12  ProductBrand_Apple             9000 non-null   int8
 13  ProductBrand_HP                9000 non-null   int8
 14  ProductBrand_Other Brands      9000 non-null   int8
 15  ProductBrand_Samsung           9000 non-null   int8
 16  ProductBrand_Sony              9000 non-null   int8
dtypes: float64(1), int64(6), int8(10)
memory usage: 580.2 KB

In [9]:
data.describe()

,ProductID,ProductPrice,CustomerAge,CustomerGender,PurchaseFrequency,CustomerSatisfaction,PurchaseIntent,ProductCategory_Headphones,ProductCategory_Laptops,ProductCategory_Smart Watches,ProductCategory_Smartphones,ProductCategory_Tablets,ProductBrand_Apple,ProductBrand_HP,ProductBrand_Other Brands,ProductBrand_Samsung,ProductBrand_Sony
count,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000,9000.000000
mean,10373.500000,1527.429195,43.347000,0.508889,10.054667,2.996000,0.566444,0.193111,0.204667,0.201111,0.204556,0.196556,0.195556,0.202222,0.197333,0.206000,0.198889
std,2598.220545,829.900898,15.055084,0.499949,5.461328,1.405301,0.495593,0.394761,0.403480,0.400853,0.403399,0.397415,0.396650,0.401679,0.398008,0.404453,0.399186
min,5874.000000,100.376358,18.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,8123.750000,809.165014,30.000000,0.000000,5.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,10373.500000,1513.024577,43.000000,1.000000,10.000000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,12623.250000,2244.415520,56.000000,1.000000,15.000000,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,14873.000000,2999.852253,69.000000,1.000000,19.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [10]:
y = data['PurchaseIntent']
x = data.drop(['PurchaseIntent'], axis = 1)

In [11]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=1)

In [12]:
y_train.shape, y_test.shape

((7200,), (1800,))

In [14]:
sc = StandardScaler()
x_train_sc = pd.DataFrame(sc.fit_transform(x_train), columns = x_train.columns, index = x_train.index)
x_test_sc = pd.DataFrame(sc.transform(x_test), columns = x_test.columns, index = x_test.index)

#### Logistic regression

In [22]:
model = LogisticRegression()
model.fit(x_train_sc, y_train)
y_train_pred = model.predict(x_train_sc)
y_test_pred = model.predict(x_test_sc)
print('Class_report_train:')
print(classification_report(y_train, y_train_pred))
print('Class_report_test:')
print(classification_report(y_test, y_test_pred))

Class_report_train:
              precision    recall  f1-score   support

           0       0.84      0.83      0.84      3140
           1       0.87      0.88      0.87      4060

    accuracy                           0.86      7200
   macro avg       0.85      0.85      0.85      7200
weighted avg       0.86      0.86      0.86      7200

Class_report_test:
              precision    recall  f1-score   support

           0       0.83      0.83      0.83       762
           1       0.87      0.87      0.87      1038

    accuracy                           0.85      1800
   macro avg       0.85      0.85      0.85      1800
weighted avg       0.85      0.85      0.85      1800

#### KNN

In [24]:
model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(x_train_sc, y_train)
y_train_pred = model_knn.predict(x_train_sc)
y_test_pred = model_knn.predict(x_test_sc)
print('Class_report_train:')
print(classification_report(y_train, y_train_pred))
print('Class_report_test:')
print(classification_report(y_test, y_test_pred))

Class_report_train:
              precision    recall  f1-score   support

           0       0.92      0.90      0.91      3140
           1       0.92      0.94      0.93      4060

    accuracy                           0.92      7200
   macro avg       0.92      0.92      0.92      7200
weighted avg       0.92      0.92      0.92      7200

Class_report_test:
              precision    recall  f1-score   support

           0       0.86      0.83      0.84       762
           1       0.88      0.90      0.89      1038

    accuracy                           0.87      1800
   macro avg       0.87      0.86      0.87      1800
weighted avg       0.87      0.87      0.87      1800

### GaussianNB

In [25]:
model_nb = GaussianNB()
model_nb.fit(x_train_sc, y_train)
y_train_pred = model_nb.predict(x_train_sc)
y_test_pred = model_nb.predict(x_test_sc)
print('Class_report_train:')
print(classification_report(y_train, y_train_pred))
print('Class_report_test:')
print(classification_report(y_test, y_test_pred))

Class_report_train:
              precision    recall  f1-score   support

           0       0.87      0.81      0.84      3140
           1       0.86      0.91      0.88      4060

    accuracy                           0.87      7200
   macro avg       0.87      0.86      0.86      7200
weighted avg       0.87      0.87      0.86      7200

Class_report_test:
              precision    recall  f1-score   support

           0       0.86      0.80      0.83       762
           1       0.86      0.90      0.88      1038

    accuracy                           0.86      1800
   macro avg       0.86      0.85      0.85      1800
weighted avg       0.86      0.86      0.86      1800

#### Decision Tree

In [29]:
model_dt = DecisionTreeClassifier(max_depth = 2, min_samples_split=2, min_samples_leaf=1)
model_dt.fit(x_train_sc, y_train)
y_train_pred = model_dt.predict(x_train_sc)
y_test_pred = model_dt.predict(x_test_sc)
print('Class_report_train:')
print(classification_report(y_train, y_train_pred))
print('Class_report_test:')
print(classification_report(y_test, y_test_pred))

Class_report_train:
              precision    recall  f1-score   support

           0       0.84      0.83      0.84      3140
           1       0.87      0.88      0.88      4060

    accuracy                           0.86      7200
   macro avg       0.86      0.86      0.86      7200
weighted avg       0.86      0.86      0.86      7200

Class_report_test:
              precision    recall  f1-score   support

           0       0.83      0.86      0.84       762
           1       0.89      0.87      0.88      1038

    accuracy                           0.87      1800
   macro avg       0.86      0.87      0.86      1800
weighted avg       0.87      0.87      0.87      1800

#### Random Forest

In [33]:
model_rf = RandomForestClassifier(n_estimators=100, max_depth = 2, min_samples_split=2, min_samples_leaf=1)
model_rf.fit(x_train_sc, y_train)
y_train_pred = model_rf.predict(x_train_sc)
y_test_pred = model_rf.predict(x_test_sc)
print('Class_report_train:')
print(classification_report(y_train, y_train_pred))
print('Class_report_test:')
print(classification_report(y_test, y_test_pred))

Class_report_train:
              precision    recall  f1-score   support

           0       0.95      0.75      0.84      3140
           1       0.84      0.97      0.90      4060

    accuracy                           0.88      7200
   macro avg       0.89      0.86      0.87      7200
weighted avg       0.89      0.88      0.87      7200

Class_report_test:
              precision    recall  f1-score   support

           0       0.95      0.78      0.86       762
           1       0.86      0.97      0.91      1038

    accuracy                           0.89      1800
   macro avg       0.90      0.88      0.88      1800
weighted avg       0.90      0.89      0.89      1800