#### Loan_approval

In [46]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report
from sklearn.preprocessing import StandardScaler

In [25]:
data = pd.read_csv('loan_approval.csv')
data

,name,city,income,credit_score,loan_amount,years_employed,points,loan_approved
0,Allison Hill,East Jill,113810,389,39698,27,50.0,False
1,Brandon Hall,New Jamesside,44592,729,15446,28,55.0,False
2,Rhonda Smith,Lake Roberto,33278,584,11189,13,45.0,False
3,Gabrielle Davis,West Melanieview,127196,344,48823,29,50.0,False
4,Valerie Gray,Mariastad,66048,496,47174,4,25.0,False
...,...,...,...,...,...,...,...,...
1995,James Schaefer,Robertton,92163,770,12251,13,85.0,True
1996,Diana Lin,New Frank,38799,635,48259,17,40.0,False
1997,Brandon Meyer,East Haley,41957,763,16752,5,60.0,True
1998,Jason Price,Adamland,139022,360,24031,35,55.0,False
1999,Nicole Brown,New Nathantown,41188,482,31397,6,20.0,False

In [26]:
data = data.drop(['name','city'], axis = 1)
data

      income  credit_score  loan_amount  years_employed  points  loan_approved
0     113810           389        39698              27    50.0          False
1      44592           729        15446              28    55.0          False
2      33278           584        11189              13    45.0          False
3     127196           344        48823              29    50.0          False
4      66048           496        47174               4    25.0          False
...      ...           ...          ...             ...     ...            ...
1995   92163           770        12251              13    85.0           True
1996   38799           635        48259              17    40.0          False
1997   41957           763        16752               5    60.0           True
1998  139022           360        24031              35    55.0          False
1999   41188           482        31397               6    20.0          False

[2000 rows x 6 columns]

In [27]:
data['loan_approved'] = (data['loan_approved']==False).astype('int8')

In [28]:
data

      income  credit_score  loan_amount  years_employed  points  loan_approved
0     113810           389        39698              27    50.0              1
1      44592           729        15446              28    55.0              1
2      33278           584        11189              13    45.0              1
3     127196           344        48823              29    50.0              1
4      66048           496        47174               4    25.0              1
...      ...           ...          ...             ...     ...            ...
1995   92163           770        12251              13    85.0              0
1996   38799           635        48259              17    40.0              1
1997   41957           763        16752               5    60.0              0
1998  139022           360        24031              35    55.0              1
1999   41188           482        31397               6    20.0              1

[2000 rows x 6 columns]

In [29]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   income          2000 non-null   int64
 1   credit_score    2000 non-null   int64
 2   loan_amount     2000 non-null   int64
 3   years_employed  2000 non-null   int64
 4   points          2000 non-null   float64
 5   loan_approved   2000 non-null   int8
dtypes: float64(1), int64(4), int8(1)
memory usage: 80.2 KB

In [30]:
data.describe()

,income,credit_score,loan_amount,years_employed,points,loan_approved
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000
mean,90585.977000,573.946000,25308.503000,20.441000,56.680000,0.56050
std,34487.874907,160.564945,14207.320147,11.777813,18.638033,0.49645
min,30053.000000,300.000000,1022.000000,0.000000,10.000000,0.00000
25%,61296.250000,433.000000,12748.750000,10.000000,45.000000,0.00000
50%,90387.500000,576.000000,25661.500000,21.000000,55.000000,1.00000
75%,120099.750000,715.000000,37380.500000,31.000000,70.000000,1.00000
max,149964.000000,850.000000,49999.000000,40.000000,100.000000,1.00000

In [31]:
y = data['loan_approved']
x = data.drop(['loan_approved'], axis = 1)

In [32]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.2, random_state = 1)

In [33]:
y_train.shape, y_test.shape

((1600,), (400,))

In [35]:
sc = StandardScaler()
x_train_sc = pd.DataFrame(sc.fit_transform(x_train), columns = x_train.columns, index = x_train.index)
x_test_sc = pd.DataFrame(sc.transform(x_test), columns = x_test.columns, index = x_test.index)

In [36]:
model = LogisticRegression()
model.fit(x_train_sc, y_train)
y_train_pred = model.predict(x_train_sc)
y_test_pred = model.predict(x_test_sc)
print(f"accuracy_train: {accuracy_score(y_train, y_train_pred)}, accuracy_test: {accuracy_score(y_test, y_test_pred)}")
print(f"recall_train: {recall_score(y_train, y_train_pred)}, recall_test: {recall_score(y_test, y_test_pred)}")
print(f"precision_train: {precision_score(y_train, y_train_pred)}, precision_test: {accuracy_score(y_test, y_test_pred)}")
print(f"f1_train: {f1_score(y_train, y_train_pred)}, f1_test: {f1_score(y_test, y_test_pred)}")

accuracy_train: 1.0, accuracy_test: 1.0
recall_train: 1.0, recall_test: 1.0
precision_train: 1.0, precision_test: 1.0
f1_train: 1.0, f1_test: 1.0

In [38]:
print(classification_report(y_train, y_train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       704
           1       1.00      1.00      1.00       896

    accuracy                           1.00      1600
   macro avg       1.00      1.00      1.00      1600
weighted avg       1.00      1.00      1.00      1600

In [39]:
model_knn = KNeighborsClassifier(n_neighbors=3)
model_knn.fit(x_train_sc, y_train)
y_train_pred = model_knn.predict(x_train_sc)
y_test_pred = model_knn.predict(x_test_sc)
print(f"accuracy_train: {accuracy_score(y_train, y_train_pred)}, accuracy_test: {accuracy_score(y_test, y_test_pred)}")
print(f"recall_train: {recall_score(y_train, y_train_pred)}, recall_test: {recall_score(y_test, y_test_pred)}")
print(f"precision_train: {precision_score(y_train, y_train_pred)}, precision_test: {accuracy_score(y_test, y_test_pred)}")
print(f"f1_train: {f1_score(y_train, y_train_pred)}, f1_test: {f1_score(y_test, y_test_pred)}")

accuracy_train: 0.993125, accuracy_test: 0.9625
recall_train: 0.9877232142857143, recall_test: 0.9333333333333333
precision_train: 1.0, precision_test: 0.9625
f1_train: 0.9938236945536215, f1_test: 0.9655172413793104

In [40]:
model_nb= GaussianNB()
model_nb.fit(x_train_sc, y_train)
y_train_pred = model_nb.predict(x_train_sc)
y_test_pred = model_nb.predict(x_test_sc)
print(f"accuracy_train: {accuracy_score(y_train, y_train_pred)}, accuracy_test: {accuracy_score(y_test, y_test_pred)}")
print(f"recall_train: {recall_score(y_train, y_train_pred)}, recall_test: {recall_score(y_test, y_test_pred)}")
print(f"precision_train: {precision_score(y_train, y_train_pred)}, precision_test: {accuracy_score(y_test, y_test_pred)}")
print(f"f1_train: {f1_score(y_train, y_train_pred)}, f1_test: {f1_score(y_test, y_test_pred)}")

accuracy_train: 0.95375, accuracy_test: 0.975
recall_train: 0.9821428571428571, recall_test: 0.9822222222222222
precision_train: 0.9381663113006397, precision_test: 0.975
f1_train: 0.9596510359869138, f1_test: 0.9778761061946902

In [47]:
model_dt= DecisionTreeRegressor(max_depth=3, min_samples_split=2, min_samples_leaf=1, random_state=0)
model_dt.fit(x_train_sc, y_train)
y_train_pred = model_dt.predict(x_train_sc)
y_test_pred = model_dt.predict(x_test_sc)
print(f"accuracy_train: {accuracy_score(y_train, y_train_pred)}, accuracy_test: {accuracy_score(y_test, y_test_pred)}")
print(f"recall_train: {recall_score(y_train, y_train_pred)}, recall_test: {recall_score(y_test, y_test_pred)}")
print(f"precision_train: {precision_score(y_train, y_train_pred)}, precision_test: {accuracy_score(y_test, y_test_pred)}")
print(f"f1_train: {f1_score(y_train, y_train_pred)}, f1_test: {f1_score(y_test, y_test_pred)}")

accuracy_train: 1.0, accuracy_test: 1.0
recall_train: 1.0, recall_test: 1.0
precision_train: 1.0, precision_test: 1.0
f1_train: 1.0, f1_test: 1.0

In [48]:
model_rf= RandomForestClassifier(n_estimators=100, max_depth=3, min_samples_split=2, min_samples_leaf=1, random_state=0)
model_rf.fit(x_train_sc, y_train)
y_train_pred = model_rf.predict(x_train_sc)
y_test_pred = model_rf.predict(x_test_sc)
print(f"accuracy_train: {accuracy_score(y_train, y_train_pred)}, accuracy_test: {accuracy_score(y_test, y_test_pred)}")
print(f"recall_train: {recall_score(y_train, y_train_pred)}, recall_test: {recall_score(y_test, y_test_pred)}")
print(f"precision_train: {precision_score(y_train, y_train_pred)}, precision_test: {accuracy_score(y_test, y_test_pred)}")
print(f"f1_train: {f1_score(y_train, y_train_pred)}, f1_test: {f1_score(y_test, y_test_pred)}")

accuracy_train: 1.0, accuracy_test: 1.0
recall_train: 1.0, recall_test: 1.0
precision_train: 1.0, precision_test: 1.0
f1_train: 1.0, f1_test: 1.0