#### Logistic regression part 2

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, recall_score, precision_score, classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

In [48]:
data = pd.read_csv('heart.csv')
data

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [50]:
data.describe()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease
count,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000,918.000000
mean,53.510893,132.396514,198.799564,0.233115,136.809368,0.887364,0.553377
std,9.432617,18.514154,109.384145,0.423046,25.460334,1.066570,0.497414
min,28.000000,0.000000,0.000000,0.000000,60.000000,-2.600000,0.000000
25%,47.000000,120.000000,173.250000,0.000000,120.000000,0.000000,0.000000
50%,54.000000,130.000000,223.000000,0.000000,138.000000,0.600000,1.000000
75%,60.000000,140.000000,267.000000,0.000000,156.000000,1.500000,1.000000
max,77.000000,200.000000,603.000000,1.000000,202.000000,6.200000,1.000000

In [51]:
data['Sex'] = (data['Sex'] == 'M').astype('int8')

In [55]:
data = pd.get_dummies(data, columns=['ChestPainType'], dtype = int)

In [56]:
data = pd.get_dummies(data, columns = ['RestingECG'],dtype = int)

In [57]:
data = pd.get_dummies(data, columns = ['ExerciseAngina'],dtype = int)

In [58]:
data = pd.get_dummies(data, columns = ['ST_Slope'],  dtype = int)

In [59]:
data

,Age,Sex,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,40,1,140,289,0,172,0.0,0,0,1,0,0,0,1,0,1,0,0,0,1
1,49,0,160,180,0,156,1.0,1,0,0,1,0,0,1,0,1,0,0,1,0
2,37,1,130,283,0,98,0.0,0,0,1,0,0,0,0,1,1,0,0,0,1
3,48,0,138,214,0,108,1.5,1,1,0,0,0,0,1,0,0,1,0,1,0
4,54,1,150,195,0,122,0.0,0,0,0,1,0,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,1,110,264,0,132,1.2,1,0,0,0,1,0,1,0,1,0,0,1,0
914,68,1,144,193,1,141,3.4,1,1,0,0,0,0,1,0,1,0,0,1,0
915,57,1,130,131,0,115,1.2,1,1,0,0,0,0,1,0,0,1,0,1,0
916,57,0,130,236,0,174,0.0,1,0,1,0,0,1,0,0,1,0,0,1,0
917,38,1,138,175,0,173,0.0,0,0,0,1,0,0,1,0,1,0,0,0,1

In [64]:
y = data['HeartDisease']
x = data.drop(['HeartDisease'], axis = 1)

In [65]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size= 0.2, random_state= 1)

In [93]:
y_train.shape, y_test.shape

((734,), (184,))

In [66]:
from sklearn.preprocessing import StandardScaler

In [67]:
sc = StandardScaler()
x_train_sc = pd.DataFrame(sc.fit_transform(x_train), columns = x_train.columns, index = x_train.index)
x_test_sc = pd.DataFrame(sc.transform(x_test), columns = x_test.columns, index = x_test.index)

#### Logistic Regression

In [68]:
model = LogisticRegression()
model.fit(x_train_sc, y_train)
y_train_pred = model.predict(x_train_sc)
y_test_pred = model.predict(x_test_sc)

In [71]:
TP_test = TN_test = FP_test = FN_test = 0

for real, pred in zip(y_test, y_test_pred):

    if real == 1 and pred == 1:
        TP_test += 1
        
    elif real == 0 and pred == 0:
        TN_test += 1
        
    elif real == 0 and pred == 1:
        FP_test += 1
        
    elif real == 1 and pred == 0:
        FN_test += 1

print("TP_test =", TP_test)
print("TN_test =", TN_test)
print("FP_test =", FP_test)
print("FN_test =", FN_test)

TP_test = 101
TN_test = 64
FP_test = 10
FN_test = 9

In [72]:
TP_train = TN_train = FP_train = FN_train = 0

for real, pred in zip(y_train, y_train_pred):

    if real == 1 and pred == 1:
        TP_train += 1
        
    elif real == 0 and pred == 0:
        TN_train += 1
        
    elif real == 0 and pred == 1:
        FP_train += 1
        
    elif real == 1 and pred == 0:
        FN_train += 1

print("TP_train =", TP_train)
print("TN_train =", TN_train)
print("FP_train =", FP_train)
print("FN_train =", FN_train)

TP_train = 353
TN_train = 281
FP_train = 55
FN_train = 45

In [76]:
acc_train = (TP_train + TN_train)/(TP_train + TN_train + FP_train + FN_train)
recall_train = TP_train / (TP_train + FN_train)
precision_train = TP_train / (TP_train + FP_train)

In [77]:
f1_train = 2 * recall_train * precision_train / (recall_train + precision_train)

In [78]:
print("Accuracy_train: " , acc_train)
print("Recall_train: " , recall_train)
print("Precision_train: " , precision_train)
print("f1_train: " , f1_train)

Accuracy_train:  0.8637602179836512
Recall_train:  0.8869346733668342
Precision_train:  0.8651960784313726
f1_train:  0.8759305210918115

In [79]:
acc_test = (TP_test + TN_test)/(TP_test + TN_test + FP_test + FN_test)
recall_test = TP_test / (TP_test + FN_test)
precision_test = TP_test / (TP_test + FP_test)

f1_test = 2 * recall_test * precision_test / (recall_test + precision_test)

print("Accuracy_test: " , acc_test)
print("Recall_test: " , recall_test)
print("Precision_test: " , precision_test)
print("f1_test: " , f1_test)

Accuracy_test:  0.8967391304347826
Recall_test:  0.9181818181818182
Precision_test:  0.9099099099099099
f1_test:  0.914027149321267

In [94]:
from sklearn.metrics import confusion_matrix

In [95]:
cm = confusion_matrix(y_train, y_train_pred)

In [96]:
cm

array([[276,  60],
       [ 50, 348]])

#### Հիմա report-ով ստուգենք

In [80]:
print(classification_report(y_train, y_train_pred))
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.86      0.84      0.85       336
           1       0.87      0.89      0.88       398

    accuracy                           0.86       734
   macro avg       0.86      0.86      0.86       734
weighted avg       0.86      0.86      0.86       734

              precision    recall  f1-score   support

           0       0.88      0.86      0.87        74
           1       0.91      0.92      0.91       110

    accuracy                           0.90       184
   macro avg       0.89      0.89      0.89       184
weighted avg       0.90      0.90      0.90       184

In [85]:
model_knn = KNeighborsClassifier(n_neighbors=13)
model_knn.fit(x_train_sc, y_train)
y_train_pred = model_knn.predict(x_train_sc)
y_test_pred = model_knn.predict(x_test_sc)
print(classification_report(y_train, y_train_pred))
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.89      0.82      0.85       336
           1       0.86      0.91      0.89       398

    accuracy                           0.87       734
   macro avg       0.87      0.87      0.87       734
weighted avg       0.87      0.87      0.87       734

              precision    recall  f1-score   support

           0       0.89      0.85      0.87        74
           1       0.90      0.93      0.91       110

    accuracy                           0.90       184
   macro avg       0.89      0.89      0.89       184
weighted avg       0.90      0.90      0.90       184

In [86]:
model_nb = GaussianNB()
model_nb.fit(x_train_sc, y_train)
y_train_pred = model_nb.predict(x_train_sc)
y_test_pred = model_nb.predict(x_test_sc)
print(classification_report(y_train, y_train_pred))
print(classification_report(y_test, y_test_pred))

              precision    recall  f1-score   support

           0       0.85      0.82      0.83       336
           1       0.85      0.87      0.86       398

    accuracy                           0.85       734
   macro avg       0.85      0.85      0.85       734
weighted avg       0.85      0.85      0.85       734

              precision    recall  f1-score   support

           0       0.84      0.88      0.86        74
           1       0.92      0.89      0.90       110

    accuracy                           0.89       184
   macro avg       0.88      0.88      0.88       184
weighted avg       0.89      0.89      0.89       184